/**
 * Pure helpers for SIS Al Jada Cobras site — testable without a full browser.
 * Loaded before site.js; attaches to globalThis.CobrasLib.
 */
(function (global) {
  const RACE_ISO = '2027-02-13T00:00:00+04:00';
  const NAV_COLLAPSE_THRESHOLD = 48;

  const STRINGS = {
    en: {
      'nav.home': 'Home',
      'nav.members': 'Members',
      'nav.work': 'Our Work',
      'nav.news': 'News',
      'nav.game': 'Game',
      'nav.learn': 'Electric Cars 101',
      'nav.specs': 'Specs',
      'nav.checklist': 'Race Checklist',
      'nav.about': 'About Us',
      'nav.sponsors': 'Sponsor Us',
      'nav.package': 'Sponsor Package',
      'nav.resources': 'Resources',
      'nav.raceDay': 'Race Day',
      'nav.main': 'Main navigation',
      'nav.menu': 'Open menu',
      'nav.menuClose': 'Close menu',
      'skip': 'Skip to content',
      'lang.toggle': 'العربية',
      'lang.label': 'Language',
      'footer.brand': 'SIS Al Jada Cobras',
      'footer.tag': 'Student electric race team · SABIS® Al Jada · Sharjah',
      'footer.rights': 'Copyright 2026 SIS Al Jada Cobras',
      'footer.made': 'Made by Areej and Mirza',
      'footer.specsPdf': 'Specs PDF',
      'footer.packagePdf': 'Package PDF',
      'footer.visits': 'visits',
      'chat.open': 'CarGPT',
      'chat.placeholder': 'Ask CarGPT…',
      'chat.send': 'Send',
      'chat.close': 'Close',
      'chat.offlineNote': '(Works offline with local FAQ answers.)',
      'chat.aria': 'Message to CarGPT',
      'chat.dialog': 'CarGPT assistant',
      'chat.prompt48': 'How does the 48V system work?',
      'chat.promptEVGP': 'What is EVGP?',
      'chat.promptSponsor': 'How can I sponsor the team?',
      'chat.thinking': 'CarGPT is thinking…',
      'chat.liveUnavailable': 'Live CarGPT is unavailable. Using local answers.',
      'chat.emptyReply': 'Live CarGPT returned an empty reply. Using local answers.',
      'chat.timeout': 'Live CarGPT timed out. Using local answers.',
      'chat.networkOffline': 'Live CarGPT is offline. Using local answers.',
      'backTop': 'Back to top',
      'share.score': 'Share score',
      'filter.all': 'All',
      'filter.empty': 'No members in this role yet.',
      'filter.aria': 'Filter members by role',
      'analytics.notice': 'Anonymous visit counted locally (privacy-friendly).',
      'game.kicker': 'Arcade test program',
      'game.title': 'Cobra Circuit',
      'game.intro': 'A retro night run through Cobra City. Cut through traffic, evade hazards, collect battery cells, and hold your nerve as the road accelerates.',
      'game.score': 'Score',
      'game.level': 'Level',
      'game.best': 'Best',
      'game.energy': 'Energy',
      'game.sim': 'EVGP training simulation',
      'game.ready': 'Ready to strike?',
      'game.how': 'Use ← → or A / D. On mobile, tap or swipe to change lanes.',
      'game.start': 'Start race',
      'game.restart': 'Restart race',
      'game.difficulty': 'Difficulty',
      'game.charge': 'Charge',
      'game.hazard': 'Hazard',
      'game.speed': 'Speed',
      'game.kmh': 'km/h',
      'game.board': 'Local leaderboard',
      'game.boardTitle': 'Fastest runs on this device.',
      'game.record': 'New track record',
      'game.empty': 'Battery empty',
      'game.over': 'Race over',
      'game.finishCopy': 'Score {score} · {mode}. Best {best}. Race again.',
      'game.shareCopied': 'Score copied — paste anywhere to share',
      'home.eyebrow': 'EVGP · SABIS® Al Jada · Sharjah',
      'home.title1': 'Built to strike.',
      'home.title2': 'Engineered to race.',
      'home.lead': 'We are a Grades 11–12 student team turning classroom knowledge into a competition-ready electric race car—one design, test, and hard-earned improvement at a time.',
      'home.ctaBuild': 'Follow the build',
      'home.ctaCrew': 'Meet the crew',
      'home.builders': 'Student builders',
      'home.system': 'Electric system',
      'home.target': 'Competition target',
      'home.countKicker': 'Target race date · February 13, 2027',
      'home.countTitle': 'The countdown to EVGP is on.',
      'news.title': 'Workshop log',
      'news.lead': 'Short updates from the Cobras build — for families, sponsors, and the team.',
      'checklist.title': 'EVGP race-day checklist',
      'checklist.lead': 'Track readiness beside the homepage countdown (target: 13 February 2027). Progress is saved on this device.',
      'checklist.reset': 'Reset checklist',
      'checklist.back': 'Back to countdown',
      'package.title': 'Sponsor package',
      'package.lead': 'Partnership options for organizations that want to back student EV engineering in Sharjah.',
      'package.download': 'Download sponsor PDF',
      'contact.title': 'Talk to the Cobras sponsorship desk',
      'specs.download': 'Download specs PDF',
      'home.days': 'Days',
      'home.hours': 'Hours',
      'home.minutes': 'Minutes',
      'home.seconds': 'Seconds',
      'home.teamIndex': '01 / The team',
      'home.teamKicker': 'More than a school project',
      'home.teamTitle': 'One car. Many disciplines. A real starting grid.',
      'home.teamBody': 'The Cobras bring mechanics, electrical systems, safety, design, media, and race strategy into one student-led program. Every member owns part of the result—and every decision has to work on the track.',
      'home.teamLink': 'Discover our mission',
      'home.teamCap': 'The Cobras team inside the electric car project room.',
      'home.driveIndex': '02 / What drives us',
      'home.driveKicker': 'The Cobra standard',
      'home.driveTitle': 'Built around real engineering.',
      'home.p1t': 'Design with purpose',
      'home.p1b': 'We translate competition rules, driver needs, and safety constraints into a practical car layout.',
      'home.p2t': 'Build as one team',
      'home.p2b': 'Mechanical, electrical, safety, and media crews work together instead of operating in isolation.',
      'home.p3t': 'Test. Learn. Repeat.',
      'home.p3b': 'Every run gives us data. We troubleshoot, adjust, and return stronger for the next test.',
      'home.machIndex': '03 / The machine',
      'home.machKicker': 'Current build dashboard',
      'home.machTitle': 'The Cobra by the numbers.',
      'home.machBody': 'These figures reflect the current build and will evolve as testing continues.',
      'home.vLabel': 'System voltage',
      'home.wLabel': 'Total weight',
      'home.sLabel': 'Average speed',
      'home.rLabel': 'Estimated runtime',
      'home.vNote': '4 × 12V batteries',
      'home.wNote': 'Current measured build',
      'home.sNote': 'Testing benchmark',
      'home.rNote': 'Depending on load',
      'home.specsLink': 'Open the complete specification sheet',
      'home.buildIndex': '04 / The build',
      'home.buildKicker': 'From sketch to circuit',
      'home.buildTitle': 'We build the car—and the skills behind it.',
      'home.plan': 'Plan',
      'home.planBody': 'Define the targets, rules, layout, parts, and safety requirements.',
      'home.assemble': 'Assemble',
      'home.assembleBody': 'Turn the design into a physical chassis, power system, and controls.',
      'home.prove': 'Prove',
      'home.proveBody': 'Test performance, diagnose problems, and refine the car for EVGP.',
      'home.phases': 'See every phase',
      'home.engIndex': '05 / Engineering',
      'home.engKicker': 'Problems become progress',
      'home.engTitle': 'What we learn when the first idea fails.',
      'home.ch1': 'Weight balance',
      'home.ch1b': 'Uneven weight can change the way the car turns and behaves at speed.',
      'home.ch1r': 'Test component placement and adjust the balance before performance runs.',
      'home.ch2': 'Reliable wiring',
      'home.ch2b': 'Loose or unclear connections make troubleshooting slower and less safe.',
      'home.ch2r': 'Organize, secure, label, and verify the power system one circuit at a time.',
      'home.ch3': 'Driver protection',
      'home.ch3b': 'Performance only matters when the driver and crew can operate safely.',
      'home.ch3r': 'Use a kill switch, seat belt, helmet, and repeatable safety checks.',
      'home.challenge': 'Challenge',
      'home.response': 'Our response',
      'home.logIndex': '06 / Workshop log',
      'home.logKicker': 'Dated workshop notes',
      'home.logTitle': 'Latest verified updates.',
      'home.now': 'Now',
      'home.nowT': 'System testing',
      'home.nowB': 'Verify controls, electrical connections, and safe shutdown behavior.',
      'home.next': 'Next',
      'home.nextT': 'Track refinement',
      'home.nextB': 'Use driving feedback to improve stability, balance, and consistency.',
      'home.race': 'Race target',
      'home.raceT': 'February 13',
      'home.raceB': 'Prepare the car, driver, documentation, and team for competition.',
      'home.ctaKicker': 'Ready for the grid',
      'home.ctaTitle': 'Follow the Cobras from workshop to race day.',
      'home.ctaCheck': 'Race checklist',
      'home.ctaNews': 'Latest news',
      'home.ctaSpecs': 'Explore the car specs',
      'common.toBeConfirmed': 'To be confirmed',
      'common.pending': 'Pending',
      'common.awaitingSignoff': 'Awaiting team sign-off',
      'home.statusIndex': 'Current / Build status',
      'home.statusKicker': 'Published workshop snapshot',
      'home.statusTitle': 'Current priority: system testing.',
      'home.statusNote': 'This status comes from the latest workshop log, not a live telemetry feed.',
      'home.statusCompletion': 'Completion percentage',
      'home.statusCurrent': 'Current task',
      'home.statusNext': 'Next milestone',
      'home.statusCrew': 'Crew assignment',
      'home.statusUpdated': 'Latest published update: 1 July 2026',
      'home.statusLink': 'Read the dated workshop log',
      'home.problem': 'Problem',
      'home.decision': 'Decision',
      'home.result': 'Result / next test',
      'home.ch1Problem': 'Uneven weight can change how the car turns and behaves at speed.',
      'home.ch1Decision': 'Mechanics shifted battery placement after low-speed runs.',
      'home.ch1Result': 'Weight remains near 186 kg; a new weigh-in is pending after the next parts change.',
      'home.ch2Problem': 'Loose or unclear connections make troubleshooting slower and less safe.',
      'home.ch2Decision': 'The electrical crew re-checked the 48V layout, secured connectors, and re-labeled critical runs.',
      'home.ch2Result': 'The next test day has a clearer, faster troubleshooting path.',
      'home.ch3Problem': 'Performance only matters when the driver and crew can operate safely.',
      'home.ch3Decision': 'Use an emergency kill switch, seat belt, helmet, and repeatable pre-run checks.',
      'home.ch3Result': 'The hardware is documented; final race-day safety sign-off is still tracked in the checklist.',
      'home.logDate1': '1 Jul 2026',
      'home.logDate2': '18 Jun 2026',
      'home.logDate3': '4 Jun 2026',
      'home.logTag1': 'Electrical',
      'home.logTag2': 'Mechanical',
      'home.logTag3': 'Media',
      'home.logEntry1': 'Kill switch and critical-run labels checked',
      'home.logBody1': 'Connectors were secured and the 48V layout was re-labeled for faster troubleshooting.',
      'home.logEntry2': 'Battery placement shifted after low-speed runs',
      'home.logBody2': 'The build remains near 186 kg; the next parts change will be followed by another weigh-in.',
      'home.logEntry3': 'Sponsor package prepared',
      'home.logBody3': 'The media crew published the sponsor PDF and refreshed outreach materials.',
      'home.logLink': 'Open the complete workshop log',
      'data.index': 'Data / Test snapshot',
      'data.kicker': 'Recorded, estimated, or pending',
      'data.title': 'Engineering data without invented trends.',
      'data.lead': 'Bars show the latest published snapshot against a clearly labeled display scale. A run history will appear only after dated test logs exist.',
      'data.voltage': 'System voltage',
      'data.voltageScale': 'Display scale: 0–48 V · configured system',
      'data.speed': 'Average test speed',
      'data.speedScale': 'Display scale: 0–50 km/h · latest published benchmark',
      'data.weight': 'Measured build weight',
      'data.weightScale': 'Display scale: 0–250 kg · re-weigh pending',
      'data.runtime': 'Estimated runtime',
      'data.runtimeScale': 'Display scale: 0–3 hours · estimate depends on load',
      'data.reliability': 'Reliability rate',
      'data.reliabilityNote': 'A percentage will be published after dated runs and fault counts are logged.',
      'data.historyLabel': 'Test history',
      'data.historyTitle': 'Awaiting logged runs',
      'data.historyBody': 'No lap-time, voltage-under-load, acceleration, temperature, distance, or fault series has been published yet.',
      'sponsor.progressIndex': '02 / Support status',
      'sponsor.progressKicker': 'Transparent until figures are approved',
      'sponsor.progressTitle': 'What is secured—and what still needs a partner.',
      'sponsor.progressLead': 'The team has not published an approved funding target, donation total, or partner list. Unknown figures stay clearly marked instead of being estimated.',
      'sponsor.fundingTarget': 'Approved funding target',
      'sponsor.secured': 'Publicly confirmed support',
      'sponsor.noneListed': 'No commitments listed yet',
      'sponsor.deadline': 'Funding deadline',
      'sponsor.remaining': 'Remaining to goal',
      'sponsor.cannotCalculate': 'Cannot calculate until figures are approved',
      'sponsor.need1': 'Car components and replacements',
      'sponsor.need1Body': 'Electrical, mechanical, drivetrain, and control parts.',
      'sponsor.need2': 'Safety and inspection equipment',
      'sponsor.need2Body': 'Driver protection, PPE, fire safety, and inspection tools.',
      'sponsor.need3': 'Testing tools and consumables',
      'sponsor.need3Body': 'Diagnostics, data collection, track access, and consumables.',
      'sponsor.need4': 'Race transport and logistics',
      'sponsor.need4Body': 'Transport, team materials, documents, and event preparation.',
      'sponsor.seekingPartner': 'Seeking partner',
      'sponsor.needsConfirmation': 'Quantities to be confirmed',
      'sponsor.planning': 'Planning',
      'sponsor.approvalNote': 'This board changes only when the school approves figures or a partnership for publication.',
      'sponsor.contactKicker': 'Verified public channel',
      'sponsor.contactTitle': 'Start with the Cobras social account.',
      'sponsor.contactBody': 'An official school sponsorship email has not been approved for publication. Message @sisaljadacobras on Instagram or TikTok for routing to the right school contact.',
      'sponsor.chatIntro': 'Ask how your organization can support the Cobras.',
      'sponsor.chatPromptSupport': 'What support does the team need?',
      'package.contactTitle': 'Route a partnership through the team.',
      'package.contactBody': 'The official school sponsorship email is awaiting approval for publication. Message @sisaljadacobras and the team will route your organization to the correct school contact.',
      'package.instagram': 'Message on Instagram',
      'package.tiktok': 'Open TikTok',
      'news.linkSpecs': 'View the electrical specification →',
      'news.linkBuild': 'Follow the build timeline →',
      'news.linkPackage': 'Open the sponsor package →',
      'news.date4': '20 May 2026',
      'news.tagPlanning': 'Race prep',
      'news.linkRace': 'Open the Race Day hub →',
      'checklist.localTitle': 'Your planning checklist',
      'checklist.localBody': 'Progress is stored only in this browser. It does not represent the team’s official shared readiness status.',
      'checklist.hubLink': 'Open the public Race Day hub',
      'role.Mechanic': 'Mechanic',
      'role.Safety': 'Safety',
      'role.Media': 'Media',
      'role.Driver': 'Driver',
      'role.Innovation': 'Innovation',
      'member.focusLabel': 'Role focus',
      'member.assignmentLabel': 'Individual assignment',
      'member.focus.Mechanic': 'Chassis assembly and hardware checks',
      'member.focus.Safety': 'PPE, shutdown, and readiness checks',
      'member.focus.Media': 'Workshop documentation and team updates',
      'member.focus.Driver': 'Driving feedback and repeatable test runs',
      'member.focus.Innovation': 'Research and improvement concepts',
      'race.eyebrow': 'EVGP / Race-day hub',
      'race.title': 'Ready for the grid.',
      'race.lead': 'One place for the Cobras’ provisional race plan, readiness checks, driver selection, and official results when the flag falls.',
      'race.heroChecklist': 'Open race checklist',
      'race.heroBuild': 'Follow the build',
      'race.targetDateShort': '13 FEB 2027',
      'race.targetDateLabel': 'Planning target — not a confirmed event date',
      'race.eventName': 'EVGP',
      'race.eventLabel': 'Competition target',
      'race.statusValue': 'Planning',
      'race.statusLabel': 'Current race-day status',
      'race.countKicker': 'Planning target',
      'race.targetDateLong': '13 February 2027',
      'race.countTitle': 'Countdown to the target date.',
      'race.countNote': 'This clock counts to the start of the planning date; the organizer has not confirmed a race start time.',
      'race.countA11y': 'Countdown to the EVGP planning target',
      'race.days': 'Days',
      'race.hours': 'Hours',
      'race.minutes': 'Minutes',
      'race.seconds': 'Seconds',
      'race.statusIndex': 'Event status',
      'race.statusKicker': 'Confirmed facts only',
      'race.statusTitle': 'What we know right now.',
      'race.statusBody': 'This board will be updated when the organizer and school confirm official details.',
      'race.venueLabel': 'Venue',
      'race.tbc': 'To be confirmed',
      'race.venueNote': 'Awaiting official event information',
      'race.scheduleLabel': 'Schedule',
      'race.scheduleNote': 'No official session times published',
      'race.inspectionLabel': 'Inspection',
      'race.inspectionNote': 'Requirements will follow organizer guidance',
      'race.selectedDriverLabel': 'Selected driver',
      'race.selectedDriverNote': 'Selection remains pending',
      'race.driverIndex': 'Driver pool',
      'race.driverKicker': 'Selection pending',
      'race.driverTitle': 'Three candidates. One seat.',
      'race.driverBody': 'The final driver will be selected after the team’s readiness and practice process is complete.',
      'race.candidate': 'Driver candidate',
      'race.driverBasar': 'Basar Ural',
      'race.driverMansour': 'Mansour Banna',
      'race.driverTaim': 'Taim Adi',
      'race.driverPending': 'Selection pending',
      'race.sequenceIndex': 'Provisional sequence',
      'race.sequenceKicker': 'Order, not official times',
      'race.sequenceTitle': 'How race day is expected to flow.',
      'race.sequenceBody': 'The organizer’s official schedule will replace this working sequence when it is published.',
      'race.seqArrival': 'Team arrival and setup',
      'race.seqArrivalBody': 'Unload the car, tools, safety equipment, documents, and team station.',
      'race.seqCheckin': 'Registration and check-in',
      'race.seqCheckinBody': 'Complete organizer and team administration when instructed.',
      'race.seqInspection': 'Technical and safety inspection',
      'race.seqInspectionBody': 'Present the car and required documentation for official checks.',
      'race.seqBriefing': 'Driver and team briefing',
      'race.seqBriefingBody': 'Review track procedures, communications, safety, and organizer instructions.',
      'race.seqPractice': 'Practice and setup checks',
      'race.seqPracticeBody': 'Use any organizer-provided running opportunity to verify the car and driver.',
      'race.seqRace': 'Race session',
      'race.seqRaceBody': 'Compete according to the confirmed EVGP format and instructions.',
      'race.seqClose': 'Results and team pack-down',
      'race.seqCloseBody': 'Record official results, thank supporters, and return all equipment safely.',
      'race.resultsIndex': 'Official results',
      'race.resultsKicker': 'Published after the race',
      'race.resultsTitle': 'The record starts at the finish line.',
      'race.resultsBody': 'These fields will show verified organizer results only. Nothing here is a prediction.',
      'race.positionLabel': 'Official position',
      'race.resultsPending': 'Pending until race',
      'race.positionNote': 'Final organizer classification',
      'race.lapsLabel': 'Completed laps or distance',
      'race.lapsNote': 'Recorded from official results',
      'race.timeLabel': 'Official race time',
      'race.timeNote': 'Published only if supplied by EVGP',
      'race.awardsLabel': 'Awards or recognition',
      'race.awardsNote': 'Added after official confirmation',
      'race.recapKicker': 'After the finish',
      'race.recapTitle': 'The race recap will live here.',
      'race.recapBody': 'After the event, the team will publish what happened, what the car taught us, the official result, and the people who helped us reach the grid.',
      'race.recapLink': 'Read team updates',
      'race.nextKicker': 'Prepare with the Cobras',
      'race.nextTitle': 'Follow every step to the starting grid.',
      'race.nextChecklist': 'Race checklist',
      'race.nextProjects': 'Build timeline',
      'race.nextNews': 'Latest updates',
      'race.chatOpen': 'CarGPT',
      'race.chatTitle': 'CarGPT',
      'race.chatIntro': 'Ask me about the Cobras, EVGP, electric cars, or race preparation.',
      'race.chatPromptChecklist': 'What should we check before race day?',
      'race.chatPromptEVGP': 'What is EVGP?',
      'race.chatInputLabel': 'Message to CarGPT',
      'race.chatPlaceholder': 'Ask about race day…',
      'race.chatSend': 'Send',
      'race.chatClose': 'Close',
      'chat.intro': 'Ask me about the team, EVGP, or electric cars.',

    },
    ar: {
      'nav.home': 'الرئيسية',
      'nav.members': 'الأعضاء',
      'nav.work': 'عملنا',
      'nav.news': 'الأخبار',
      'nav.game': 'اللعبة',
      'nav.learn': 'السيارات الكهربائية 101',
      'nav.specs': 'المواصفات',
      'nav.checklist': 'قائمة السباق',
      'nav.about': 'من نحن',
      'nav.sponsors': 'الرعاة',
      'nav.package': 'باقة الرعاية',
      'nav.resources': 'الموارد',
      'nav.raceDay': 'يوم السباق',
      'nav.main': 'التنقل الرئيسي',
      'nav.menu': 'فتح القائمة',
      'nav.menuClose': 'إغلاق القائمة',
      'skip': 'تخطي إلى المحتوى',
      'lang.toggle': 'English',
      'lang.label': 'اللغة',
      'footer.brand': 'فريق كوبرا سيس الجادة',
      'footer.tag': 'فريق سباق كهربائي طلابي · سابيس الجادة · الشارقة',
      'footer.rights': 'حقوق النشر 2026 لفريق كوبرا سيس الجادة',
      'footer.made': 'تصميم وتطوير عريج وميرزا',
      'footer.specsPdf': 'ملف المواصفات PDF',
      'footer.packagePdf': 'ملف باقة الرعاية PDF',
      'footer.visits': 'الزيارات',
      'chat.open': 'CarGPT',
      'chat.placeholder': 'اسأل CarGPT…',
      'chat.send': 'إرسال',
      'chat.close': 'إغلاق',
      'chat.offlineNote': '(يعمل دون اتصال بإجابات محلية.)',
      'chat.aria': 'رسالة إلى CarGPT',
      'chat.dialog': 'مساعد CarGPT',
      'chat.prompt48': 'كيف يعمل نظام 48 فولت؟',
      'chat.promptEVGP': 'ما هي مسابقة EVGP؟',
      'chat.promptSponsor': 'كيف يمكنني رعاية الفريق؟',
      'chat.thinking': 'يفكر CarGPT…',
      'chat.liveUnavailable': 'خدمة CarGPT المباشرة غير متاحة. سنستخدم الإجابات المحلية.',
      'chat.emptyReply': 'لم تُرجع خدمة CarGPT المباشرة إجابة. سنستخدم الإجابات المحلية.',
      'chat.timeout': 'انتهت مهلة خدمة CarGPT المباشرة. سنستخدم الإجابات المحلية.',
      'chat.networkOffline': 'خدمة CarGPT المباشرة غير متصلة. سنستخدم الإجابات المحلية.',
      'backTop': 'العودة للأعلى',
      'share.score': 'مشاركة النتيجة',
      'filter.all': 'الكل',
      'filter.empty': 'لا أعضاء في هذا الدور بعد.',
      'filter.aria': 'تصفية الأعضاء حسب الدور',
      'analytics.notice': 'تُحتسب الزيارة محليًا وبشكل مجهول حفاظًا على الخصوصية.',
      'game.kicker': 'محاكاة سباق بأسلوب ألعاب الآركيد',
      'game.title': 'دائرة الكوبرا',
      'game.intro': 'سباق ليلي بأسلوب قديم عبر مدينة الكوبرا. تجاوز المرور، تجنب المخاطر، اجمع خلايا البطارية، وثبّت أعصابك مع تسارع الطريق.',
      'game.score': 'النتيجة',
      'game.level': 'المستوى',
      'game.best': 'الأفضل',
      'game.energy': 'الطاقة',
      'game.sim': 'محاكاة تدريب EVGP',
      'game.ready': 'هل أنت مستعد للانطلاق؟',
      'game.how': 'استخدم ← → أو A / D. على الجوال: المس أو اسحب لتغيير المسار.',
      'game.start': 'ابدأ السباق',
      'game.restart': 'أعد السباق',
      'game.difficulty': 'الصعوبة',
      'game.charge': 'شحن',
      'game.hazard': 'خطر',
      'game.speed': 'السرعة',
      'game.kmh': 'كم/س',
      'game.board': 'لوحة المتصدرين المحلية',
      'game.boardTitle': 'أسرع الجولات على هذا الجهاز.',
      'game.record': 'رقم قياسي جديد',
      'game.empty': 'البطارية فارغة',
      'game.over': 'انتهى السباق',
      'game.finishCopy': 'النتيجة {score} · {mode}. الأفضل {best}. انطلق مجددًا.',
      'game.shareCopied': 'تم نسخ النتيجة — الصقها في أي مكان',
      'home.eyebrow': 'EVGP · سابيس الجادة · الشارقة',
      'home.title1': 'صُنعت للانقضاض.',
      'home.title2': 'صُممت للسباق.',
      'home.lead': 'نحن فريق طلابي من الصفين 11–12 نحوّل معرفة الصف إلى سيارة سباق كهربائية جاهزة للمنافسة—تصميماً واختباراً وتحسيناً في كل مرة.',
      'home.ctaBuild': 'تابع البناء',
      'home.ctaCrew': 'تعرّف على الفريق',
      'home.builders': 'طلاب مشاركون في البناء',
      'home.system': 'نظام كهربائي',
      'home.target': 'هدف المسابقة',
      'home.countKicker': 'موعد السباق المستهدف · 13 فبراير 2027',
      'home.countTitle': 'العدّ التنازلي لـ EVGP بدأ.',
      'news.title': 'سجل الورشة',
      'news.lead': 'تحديثات قصيرة من بناء الكوبرا — للعائلات والرعاة والفريق.',
      'checklist.title': 'قائمة يوم سباق EVGP',
      'checklist.lead': 'تتبع الجاهزية بجانب عدّاد الصفحة الرئيسية (الهدف: 13 فبراير 2027). يُحفظ التقدم على هذا الجهاز.',
      'checklist.reset': 'إعادة تعيين القائمة',
      'checklist.back': 'العودة إلى العدّ التنازلي',
      'package.title': 'باقة الرعاية',
      'package.lead': 'خيارات شراكة للمؤسسات التي تريد دعم هندسة السيارات الكهربائية الطلابية في الشارقة.',
      'package.download': 'تنزيل ملف الرعاية بصيغة PDF',
      'contact.title': 'تواصل مع مكتب رعاية الكوبرا',
      'specs.download': 'تنزيل مواصفات PDF',
      'home.days': 'أيام',
      'home.hours': 'ساعات',
      'home.minutes': 'دقائق',
      'home.seconds': 'ثوانٍ',
      'home.teamIndex': '01 / الفريق',
      'home.teamKicker': 'أكثر من مشروع مدرسي',
      'home.teamTitle': 'سيارة واحدة. تخصصات كثيرة. خط انطلاق حقيقي.',
      'home.teamBody': 'يجمع فريق الكوبرا الميكانيكا والكهرباء والسلامة والتصميم والإعلام واستراتيجية السباق في برنامج طلابي واحد. كل عضو يملك جزءاً من النتيجة—وكل قرار يجب أن يعمل على المسار.',
      'home.teamLink': 'اكتشف مهمتنا',
      'home.teamCap': 'فريق الكوبرا داخل غرفة مشروع السيارة الكهربائية.',
      'home.driveIndex': '02 / ما يدفعنا',
      'home.driveKicker': 'معيار الكوبرا',
      'home.driveTitle': 'مبني حول هندسة حقيقية.',
      'home.p1t': 'تصميم بهدف',
      'home.p1b': 'نحوّل قوانين المسابقة واحتياجات السائق وقيود السلامة إلى تخطيط عملي للسيارة.',
      'home.p2t': 'نبني كفريق واحد',
      'home.p2b': 'فرق الميكانيكا والكهرباء والسلامة والإعلام تعمل معاً بدل العمل المنفصل.',
      'home.p3t': 'اختبر. تعلّم. كرّر.',
      'home.p3b': 'كل جولة تعطينا بيانات. نصلح ونضبط ونعود أقوى للاختبار التالي.',
      'home.machIndex': '03 / الآلة',
      'home.machKicker': 'لوحة بيانات السيارة الحالية',
      'home.machTitle': 'الكوبرا بالأرقام.',
      'home.machBody': 'هذه الأرقام تعكس البناء الحالي وستتغير مع استمرار الاختبار.',
      'home.vLabel': 'جهد النظام',
      'home.wLabel': 'الوزن الإجمالي',
      'home.sLabel': 'متوسط السرعة',
      'home.rLabel': 'مدة التشغيل التقديرية',
      'home.vNote': '4 × بطاريات 12V',
      'home.wNote': 'القياس الحالي',
      'home.sNote': 'معيار الاختبار',
      'home.rNote': 'حسب الحمل',
      'home.specsLink': 'افتح ورقة المواصفات الكاملة',
      'home.buildIndex': '04 / البناء',
      'home.buildKicker': 'من الرسم إلى الدائرة',
      'home.buildTitle': 'نبني السيارة—والمهارات خلفها.',
      'home.plan': 'خطّط',
      'home.planBody': 'حدد الأهداف والقوانين والتخطيط والقطع ومتطلبات السلامة.',
      'home.assemble': 'ركّب',
      'home.assembleBody': 'حوّل التصميم إلى هيكل ونظام طاقة وتحكم فعلي.',
      'home.prove': 'أثبت',
      'home.proveBody': 'اختبر الأداء، وشخّص الأعطال، وحسّن السيارة لـ EVGP.',
      'home.phases': 'شاهد كل مرحلة',
      'home.engIndex': '05 / الهندسة',
      'home.engKicker': 'المشاكل تصبح تقدماً',
      'home.engTitle': 'ماذا نتعلم عندما تفشل الفكرة الأولى.',
      'home.ch1': 'توازن الوزن',
      'home.ch1b': 'الوزن غير المتساوي يغيّر طريقة الانعطاف والسلوك عند السرعة.',
      'home.ch1r': 'نختبر وضع المكوّنات ونضبط التوازن قبل جولات الأداء.',
      'home.ch2': 'توصيلات كهربائية موثوقة',
      'home.ch2b': 'الوصلات الضعيفة أو غير الواضحة تبطئ الإصلاح وتقلل السلامة.',
      'home.ch2r': 'ننظم ونثبت ونعلّم ونتحقق من نظام الطاقة دائرة بدائرة.',
      'home.ch3': 'حماية السائق',
      'home.ch3b': 'الأداء لا يهم إلا عندما يعمل السائق والفريق بأمان.',
      'home.ch3r': 'نستخدم مفتاح إيقاف، حزام أمان، خوذة، وفحوصات سلامة متكررة.',
      'home.challenge': 'التحدي',
      'home.response': 'حلّنا',
      'home.logIndex': '06 / سجل الورشة',
      'home.logKicker': 'ملاحظات ورشة مؤرخة',
      'home.logTitle': 'أحدث التحديثات الموثقة.',
      'home.now': 'الآن',
      'home.nowT': 'اختبار الأنظمة',
      'home.nowB': 'التحقق من التحكم والوصلات الكهربائية وإيقاف التشغيل الآمن.',
      'home.next': 'التالي',
      'home.nextT': 'تحسين المسار',
      'home.nextB': 'استخدام ملاحظات القيادة لتحسين الثبات والتوازن والاستقرار.',
      'home.race': 'هدف السباق',
      'home.raceT': '13 فبراير',
      'home.raceB': 'تجهيز السيارة والسائق والوثائق والفريق للمسابقة.',
      'home.ctaKicker': 'جاهزون لخط الانطلاق',
      'home.ctaTitle': 'تابع الكوبرا من الورشة إلى يوم السباق.',
      'home.ctaCheck': 'قائمة السباق',
      'home.ctaNews': 'آخر الأخبار',
      'home.ctaSpecs': 'استكشف مواصفات السيارة',
      'common.toBeConfirmed': 'قيد التأكيد',
      'common.pending': 'قيد الانتظار',
      'common.awaitingSignoff': 'بانتظار اعتماد الفريق',
      'home.statusIndex': 'الحالي / حالة البناء',
      'home.statusKicker': 'ملخص منشور من الورشة',
      'home.statusTitle': 'الأولوية الحالية: اختبار الأنظمة.',
      'home.statusNote': 'تعتمد هذه الحالة على أحدث سجل منشور للورشة، وليست بثًا مباشرًا للبيانات.',
      'home.statusCompletion': 'نسبة الإنجاز',
      'home.statusCurrent': 'المهمة الحالية',
      'home.statusNext': 'المحطة التالية',
      'home.statusCrew': 'توزيع فريق العمل',
      'home.statusUpdated': 'آخر تحديث منشور: 1 يوليو 2026',
      'home.statusLink': 'اقرأ سجل الورشة المؤرخ',
      'home.problem': 'المشكلة',
      'home.decision': 'القرار الهندسي',
      'home.result': 'النتيجة / الاختبار التالي',
      'home.ch1Problem': 'قد يغيّر توزيع الوزن غير المتوازن طريقة انعطاف السيارة وسلوكها عند السرعة.',
      'home.ch1Decision': 'عدّل فريق الميكانيكا مواضع البطاريات بعد جولات منخفضة السرعة.',
      'home.ch1Result': 'ما زال الوزن قريبًا من 186 كغ، وستُعاد عملية الوزن بعد تغيير القطع التالي.',
      'home.ch2Problem': 'تجعل التوصيلات غير الواضحة أو غير المحكمة اكتشاف الأعطال أبطأ وأقل أمانًا.',
      'home.ch2Decision': 'أعاد فريق الكهرباء فحص نظام 48 فولت وثبّت الموصلات وجدّد تسميات التوصيلات المهمة.',
      'home.ch2Result': 'أصبح مسار اكتشاف الأعطال في يوم الاختبار التالي أوضح وأسرع.',
      'home.ch3Problem': 'لا قيمة للأداء ما لم يتمكن السائق والفريق من التشغيل بأمان.',
      'home.ch3Decision': 'استخدام مفتاح إيقاف طارئ وحزام أمان وخوذة وفحوصات ثابتة قبل كل جولة.',
      'home.ch3Result': 'المعدات موثقة، وما زال اعتماد السلامة النهائي ليوم السباق ضمن قائمة الجاهزية.',
      'home.logDate1': '1 يوليو 2026',
      'home.logDate2': '18 يونيو 2026',
      'home.logDate3': '4 يونيو 2026',
      'home.logTag1': 'الكهرباء',
      'home.logTag2': 'الميكانيكا',
      'home.logTag3': 'الإعلام',
      'home.logEntry1': 'فحص مفتاح الإيقاف وتسميات التوصيلات المهمة',
      'home.logBody1': 'ثُبّتت الموصلات وأعيدت تسمية توصيلات نظام 48 فولت لتسريع اكتشاف الأعطال.',
      'home.logEntry2': 'تعديل مواضع البطاريات بعد جولات منخفضة السرعة',
      'home.logBody2': 'ما زال وزن السيارة قريبًا من 186 كغ، وستلي عملية تغيير القطع عملية وزن جديدة.',
      'home.logEntry3': 'إعداد باقة الرعاية',
      'home.logBody3': 'نشر فريق الإعلام ملف الرعاية وحدّث مواد التواصل مع الشركاء.',
      'home.logLink': 'افتح سجل الورشة الكامل',
      'data.index': 'البيانات / ملخص الاختبار',
      'data.kicker': 'مقاس أو مقدّر أو قيد الانتظار',
      'data.title': 'بيانات هندسية بلا اتجاهات مختلقة.',
      'data.lead': 'تعرض الأشرطة أحدث ملخص منشور مقابل نطاق عرض واضح. لن يظهر سجل للجولات إلا بعد توفر اختبارات مؤرخة.',
      'data.voltage': 'جهد النظام',
      'data.voltageScale': 'نطاق العرض: 0–48 فولت · إعداد النظام',
      'data.speed': 'متوسط سرعة الاختبار',
      'data.speedScale': 'نطاق العرض: 0–50 كم/س · أحدث معيار منشور',
      'data.weight': 'وزن السيارة المقاس',
      'data.weightScale': 'نطاق العرض: 0–250 كغ · إعادة الوزن قيد الانتظار',
      'data.runtime': 'مدة التشغيل المقدّرة',
      'data.runtimeScale': 'نطاق العرض: 0–3 ساعات · التقدير يعتمد على الحمل',
      'data.reliability': 'معدل الموثوقية',
      'data.reliabilityNote': 'ستنشر النسبة بعد تسجيل الجولات المؤرخة وعدد الأعطال.',
      'data.historyLabel': 'سجل الاختبارات',
      'data.historyTitle': 'بانتظار جولات مسجلة',
      'data.historyBody': 'لم تُنشر بعد بيانات زمن اللفة أو الجهد تحت الحمل أو التسارع أو الحرارة أو المسافة أو الأعطال.',
      'sponsor.progressIndex': '02 / حالة الدعم',
      'sponsor.progressKicker': 'شفافية حتى اعتماد الأرقام',
      'sponsor.progressTitle': 'ما تم تأمينه وما زال يحتاج إلى شريك.',
      'sponsor.progressLead': 'لم ينشر الفريق هدفًا تمويليًا معتمدًا أو إجمالي التبرعات أو قائمة الشركاء. تبقى الأرقام غير المعروفة واضحة بدل تقديرها.',
      'sponsor.fundingTarget': 'الهدف التمويلي المعتمد',
      'sponsor.secured': 'الدعم المؤكد علنًا',
      'sponsor.noneListed': 'لا توجد التزامات منشورة بعد',
      'sponsor.deadline': 'الموعد النهائي للتمويل',
      'sponsor.remaining': 'المتبقي للوصول إلى الهدف',
      'sponsor.cannotCalculate': 'لا يمكن حسابه حتى اعتماد الأرقام',
      'sponsor.need1': 'قطع السيارة والبدائل',
      'sponsor.need1Body': 'قطع كهربائية وميكانيكية ونظام نقل الحركة والتحكم.',
      'sponsor.need2': 'معدات السلامة والفحص',
      'sponsor.need2Body': 'حماية السائق ومعدات الوقاية والسلامة من الحريق وأدوات الفحص.',
      'sponsor.need3': 'أدوات الاختبار والمواد المستهلكة',
      'sponsor.need3Body': 'التشخيص وجمع البيانات والوصول إلى المسار والمواد المستهلكة.',
      'sponsor.need4': 'نقل السباق والخدمات اللوجستية',
      'sponsor.need4Body': 'النقل ومواد الفريق والوثائق والاستعداد للفعالية.',
      'sponsor.seekingPartner': 'نبحث عن شريك',
      'sponsor.needsConfirmation': 'الكميات قيد التأكيد',
      'sponsor.planning': 'قيد التخطيط',
      'sponsor.approvalNote': 'تتغير هذه اللوحة فقط عند اعتماد المدرسة للأرقام أو السماح بنشر شراكة.',
      'sponsor.contactKicker': 'قناة عامة موثقة',
      'sponsor.contactTitle': 'ابدأ عبر حساب كوبرا على التواصل الاجتماعي.',
      'sponsor.contactBody': 'لم يُعتمد بعد بريد مدرسي رسمي للرعاية للنشر. راسل @sisaljadacobras عبر إنستغرام أو تيك توك للوصول إلى جهة الاتصال المدرسية المناسبة.',
      'sponsor.chatIntro': 'اسأل كيف يمكن لمؤسستك دعم فريق كوبرا.',
      'sponsor.chatPromptSupport': 'ما نوع الدعم الذي يحتاجه الفريق؟',
      'package.contactTitle': 'ابدأ الشراكة عبر الفريق.',
      'package.contactBody': 'البريد المدرسي الرسمي للرعاية بانتظار اعتماد النشر. راسل @sisaljadacobras وسيصل طلب مؤسستك إلى جهة الاتصال المدرسية المناسبة.',
      'package.instagram': 'راسلنا عبر إنستغرام',
      'package.tiktok': 'افتح تيك توك',
      'news.linkSpecs': 'اطّلع على المواصفات الكهربائية ←',
      'news.linkBuild': 'تابع مراحل البناء ←',
      'news.linkPackage': 'افتح باقة الرعاية ←',
      'news.date4': '20 مايو 2026',
      'news.tagPlanning': 'استعداد السباق',
      'news.linkRace': 'افتح مركز يوم السباق ←',
      'checklist.localTitle': 'قائمة التخطيط الخاصة بك',
      'checklist.localBody': 'يُحفظ التقدم في هذا المتصفح فقط، ولا يمثل حالة الجاهزية الرسمية المشتركة للفريق.',
      'checklist.hubLink': 'افتح مركز يوم السباق العام',
      'role.Mechanic': 'الميكانيكا',
      'role.Safety': 'السلامة',
      'role.Media': 'الإعلام',
      'role.Driver': 'القيادة',
      'role.Innovation': 'الابتكار',
      'member.focusLabel': 'محور الدور',
      'member.assignmentLabel': 'المهمة الفردية',
      'member.focus.Mechanic': 'تجميع الهيكل وفحص المثبتات',
      'member.focus.Safety': 'معدات الوقاية والإيقاف وفحوصات الجاهزية',
      'member.focus.Media': 'توثيق الورشة وتحديثات الفريق',
      'member.focus.Driver': 'ملاحظات القيادة وجولات الاختبار المتكررة',
      'member.focus.Innovation': 'البحث وأفكار التحسين',
      'race.eyebrow': 'EVGP / مركز يوم السباق',
      'race.title': 'جاهزون لخط الانطلاق.',
      'race.lead': 'مكان واحد لخطة السباق المؤقتة وفحوصات الجاهزية واختيار السائق والنتائج الرسمية عند انتهاء السباق.',
      'race.heroChecklist': 'افتح قائمة السباق',
      'race.heroBuild': 'تابع البناء',
      'race.targetDateShort': '13 فبراير 2027',
      'race.targetDateLabel': 'هدف تخطيطي — وليس موعدًا رسميًا مؤكدًا',
      'race.eventName': 'EVGP',
      'race.eventLabel': 'المسابقة المستهدفة',
      'race.statusValue': 'التخطيط',
      'race.statusLabel': 'حالة يوم السباق الحالية',
      'race.countKicker': 'الهدف التخطيطي',
      'race.targetDateLong': '13 فبراير 2027',
      'race.countTitle': 'العد التنازلي إلى التاريخ المستهدف.',
      'race.countNote': 'تصل الساعة إلى بداية التاريخ التخطيطي؛ ولم يؤكد المنظم وقت انطلاق السباق.',
      'race.countA11y': 'العد التنازلي إلى هدف EVGP التخطيطي',
      'race.days': 'أيام',
      'race.hours': 'ساعات',
      'race.minutes': 'دقائق',
      'race.seconds': 'ثوانٍ',
      'race.statusIndex': 'حالة الفعالية',
      'race.statusKicker': 'الحقائق المؤكدة فقط',
      'race.statusTitle': 'ما نعرفه الآن.',
      'race.statusBody': 'ستتحدث هذه اللوحة عندما يؤكد المنظم والمدرسة التفاصيل الرسمية.',
      'race.venueLabel': 'الموقع',
      'race.tbc': 'قيد التأكيد',
      'race.venueNote': 'بانتظار معلومات الفعالية الرسمية',
      'race.scheduleLabel': 'الجدول',
      'race.scheduleNote': 'لم تُنشر أوقات الجلسات الرسمية',
      'race.inspectionLabel': 'الفحص الفني',
      'race.inspectionNote': 'ستتبع المتطلبات تعليمات المنظم',
      'race.selectedDriverLabel': 'السائق المختار',
      'race.selectedDriverNote': 'الاختيار ما زال قيد الانتظار',
      'race.driverIndex': 'مجموعة السائقين',
      'race.driverKicker': 'الاختيار قيد الانتظار',
      'race.driverTitle': 'ثلاثة مرشحين. مقعد واحد.',
      'race.driverBody': 'سيُختار السائق النهائي بعد اكتمال عملية الجاهزية والتدريب.',
      'race.candidate': 'مرشح للقيادة',
      'race.driverBasar': 'Basar Ural',
      'race.driverMansour': 'Mansour Banna',
      'race.driverTaim': 'Taim Adi',
      'race.driverPending': 'الاختيار قيد الانتظار',
      'race.sequenceIndex': 'التسلسل المؤقت',
      'race.sequenceKicker': 'ترتيب بلا أوقات رسمية',
      'race.sequenceTitle': 'كيف يُتوقع أن يسير يوم السباق.',
      'race.sequenceBody': 'سيحل جدول المنظم الرسمي محل هذا التسلسل عند نشره.',
      'race.seqArrival': 'وصول الفريق والتجهيز',
      'race.seqArrivalBody': 'تفريغ السيارة والأدوات ومعدات السلامة والوثائق وتجهيز مساحة الفريق.',
      'race.seqCheckin': 'التسجيل وتأكيد الحضور',
      'race.seqCheckinBody': 'إكمال إجراءات المنظم والفريق عند صدور التعليمات.',
      'race.seqInspection': 'الفحص الفني وفحص السلامة',
      'race.seqInspectionBody': 'تقديم السيارة والوثائق المطلوبة للفحوصات الرسمية.',
      'race.seqBriefing': 'إحاطة السائق والفريق',
      'race.seqBriefingBody': 'مراجعة إجراءات المسار والتواصل والسلامة وتعليمات المنظم.',
      'race.seqPractice': 'التدريب وفحوصات الإعداد',
      'race.seqPracticeBody': 'استغلال أي فرصة تشغيل يتيحها المنظم للتحقق من السيارة والسائق.',
      'race.seqRace': 'جلسة السباق',
      'race.seqRaceBody': 'المنافسة وفق صيغة EVGP وتعليماتها المؤكدة.',
      'race.seqClose': 'النتائج وتجميع معدات الفريق',
      'race.seqCloseBody': 'تسجيل النتائج الرسمية وشكر الداعمين وإعادة جميع المعدات بأمان.',
      'race.resultsIndex': 'النتائج الرسمية',
      'race.resultsKicker': 'تنشر بعد السباق',
      'race.resultsTitle': 'يبدأ السجل عند خط النهاية.',
      'race.resultsBody': 'ستعرض هذه الخانات نتائج المنظم الموثقة فقط، ولا تتضمن أي توقعات.',
      'race.positionLabel': 'المركز الرسمي',
      'race.resultsPending': 'بانتظار السباق',
      'race.positionNote': 'التصنيف النهائي من المنظم',
      'race.lapsLabel': 'اللفات أو المسافة المكتملة',
      'race.lapsNote': 'تسجل من النتائج الرسمية',
      'race.timeLabel': 'زمن السباق الرسمي',
      'race.timeNote': 'ينشر فقط إذا قدمته EVGP',
      'race.awardsLabel': 'الجوائز أو التكريم',
      'race.awardsNote': 'تضاف بعد التأكيد الرسمي',
      'race.recapKicker': 'بعد خط النهاية',
      'race.recapTitle': 'سيُنشر ملخص السباق هنا.',
      'race.recapBody': 'بعد الفعالية سينشر الفريق ما حدث وما تعلمناه من السيارة والنتيجة الرسمية ومن ساعدنا في الوصول إلى خط الانطلاق.',
      'race.recapLink': 'اقرأ تحديثات الفريق',
      'race.nextKicker': 'استعد مع فريق كوبرا',
      'race.nextTitle': 'تابع كل خطوة إلى خط الانطلاق.',
      'race.nextChecklist': 'قائمة السباق',
      'race.nextProjects': 'مراحل البناء',
      'race.nextNews': 'آخر التحديثات',
      'race.chatOpen': 'CarGPT',
      'race.chatTitle': 'CarGPT',
      'race.chatIntro': 'اسألني عن فريق كوبرا أو EVGP أو السيارات الكهربائية أو الاستعداد للسباق.',
      'race.chatPromptChecklist': 'ما الذي يجب فحصه قبل يوم السباق؟',
      'race.chatPromptEVGP': 'ما هي مسابقة EVGP؟',
      'race.chatInputLabel': 'رسالة إلى CarGPT',
      'race.chatPlaceholder': 'اسأل عن يوم السباق…',
      'race.chatSend': 'إرسال',
      'race.chatClose': 'إغلاق',
      'chat.intro': 'اسألني عن الفريق أو EVGP أو السيارات الكهربائية.',

    }
  };

  const RESOURCE_ITEMS = [
    { href: 'race-day.html', key: 'nav.raceDay', match: ['race-day.html'] },
    { href: 'news.html', key: 'nav.news', match: ['news.html'] },
    { href: '101.html', key: 'nav.learn', match: ['101.html'] },
    { href: 'checklist.html', key: 'nav.checklist', match: ['checklist.html'] }
  ];

  const NAV_ITEMS = [
    { href: 'index.html', key: 'nav.home', match: ['index.html', '', '/'] },
    { href: 'members.html', key: 'nav.members', match: ['members.html'] },
    { href: 'projects.html', key: 'nav.work', match: ['projects.html'] },
    { href: 'specs.html', key: 'nav.specs', match: ['specs.html'] },
    { href: 'game.html', key: 'nav.game', match: ['game.html'] },
    { id: 'resources', key: 'nav.resources', children: RESOURCE_ITEMS },
    { href: 'about.html', key: 'nav.about', match: ['about.html'] },
    { href: 'sponsors.html', key: 'nav.sponsors', match: ['sponsors.html'] }
  ];

  function normalizeLang(lang) {
    const value = String(lang || 'en').toLowerCase();
    return value.startsWith('ar') ? 'ar' : 'en';
  }

  function t(lang, key) {
    const code = normalizeLang(lang);
    return (STRINGS[code] && STRINGS[code][key]) || (STRINGS.en[key]) || key;
  }

  function shouldCollapseNav(scrollY, threshold) {
    const limit = threshold == null ? NAV_COLLAPSE_THRESHOLD : Number(threshold);
    return Number(scrollY) > limit;
  }

  function currentPageName(pathname) {
    const raw = String(pathname || '').split(/[?#]/)[0];
    const base = raw.split('/').pop() || 'index.html';
    if (!base || base === 'index') return 'index.html';
    return base.includes('.') ? base : `${base}.html`;
  }

  function isCurrentNav(item, pageName) {
    const matches = Array.isArray(item && item.match) ? item.match : [];
    const direct = matches.some(m => m === pageName || (m === 'index.html' && (pageName === '' || pageName === '/')));
    return direct || (Array.isArray(item && item.children) && item.children.some(child => isCurrentNav(child, pageName)));
  }

  function countdownParts(nowMs, targetMs) {
    const remaining = Math.max(0, Number(targetMs) - Number(nowMs));
    return {
      days: Math.floor(remaining / 86400000),
      hours: Math.floor(remaining / 3600000) % 24,
      minutes: Math.floor(remaining / 60000) % 60,
      seconds: Math.floor(remaining / 1000) % 60,
      remaining,
      done: remaining <= 0
    };
  }

  function buildScoreShareText(payload) {
    const score = Math.max(0, Math.floor(Number(payload && payload.score) || 0));
    const best = Math.max(0, Math.floor(Number(payload && payload.best) || 0));
    const mode = String((payload && payload.mode) || 'f2').toUpperCase();
    const level = Math.max(1, Math.floor(Number(payload && payload.level) || 1));
    return [
      'SIS Al Jada Cobras — Cobra Circuit',
      `Mode: ${mode} · Level ${level}`,
      `Score: ${String(score).padStart(5, '0')}`,
      `Best: ${String(best).padStart(5, '0')}`,
      'Built to strike. Engineered to race.'
    ].join('\n');
  }

  function checklistProgress(items) {
    const list = Array.isArray(items) ? items : [];
    const total = list.length;
    const done = list.filter(item => item && item.done).length;
    const percent = total === 0 ? 0 : Math.round((done / total) * 100);
    return { total, done, percent, remaining: Math.max(0, total - done) };
  }

  function resolveChatConfig(runtime) {
    const rt = runtime || {};
    const storage = rt.storage || {};
    const endpoint =
      storage.CARGPT_ENDPOINT ||
      rt.CARGPT_ENDPOINT ||
      'https://cobras-chat.areej-dridi.workers.dev';
    const apiKey = storage.CARGPT_API_KEY || rt.CARGPT_API_KEY || '';
    return {
      endpoint: String(endpoint),
      apiKey: String(apiKey || ''),
      hasKey: Boolean(apiKey && String(apiKey).trim())
    };
  }

  function trackPageView(store, path, nowMs) {
    const data = store && typeof store === 'object' ? store : {};
    const page = currentPageName(path);
    const day = new Date(Number(nowMs) || Date.now()).toISOString().slice(0, 10);
    data.total = (Number(data.total) || 0) + 1;
    data.byPage = data.byPage || {};
    data.byPage[page] = (Number(data.byPage[page]) || 0) + 1;
    data.byDay = data.byDay || {};
    data.byDay[day] = (Number(data.byDay[day]) || 0) + 1;
    data.lastPath = page;
    data.lastAt = Number(nowMs) || Date.now();
    return data;
  }

  function localFaqReply(text, requestedLang) {
    const q = String(text || '').toLowerCase();
    if (normalizeLang(requestedLang) === 'ar') {
      const arabicAnswers = [
        { keys: ['رعا', 'دعم', 'تمويل', 'شريك', 'تواصل'], reply: 'يمكنك فتح صفحتي «رعاية الفريق» و«باقة الرعاية» لمعرفة الاحتياجات وخيارات الشراكة والتواصل مع الفريق.' },
        { keys: ['48', 'بطاري', 'جهد', 'كهرب', 'طاقة'], reply: 'تعمل السيارة بنظام كهربائي بجهد 48 فولت مكوّن من أربع بطاريات 12 فولت موصولة على التوالي، مع توصيلات معنونة ومفتاح إيقاف طارئ.' },
        { keys: ['evgp', 'مسابقة', 'سباق', 'فبراير', 'قائمة'], reply: 'التاريخ التخطيطي المستهدف هو 13 فبراير 2027. افتح «يوم السباق» للحقائق المؤكدة والنتائج عند توفرها، واستخدم «قائمة السباق» للتخطيط المحفوظ على جهازك.' },
        { keys: ['خبر', 'تحديث', 'جديد'], reply: 'راجع صفحة «الأخبار» للاطلاع على آخر تحديثات ورشة فريق كوبرا.' },
        { keys: ['فريق', 'عضو', 'طلاب', 'من أنتم', 'عدد'], reply: 'نحن نحو 19 طالبًا وطالبة من سابيس® الجادة في الشارقة. تعرّف إلى الفريق في صفحة «الأعضاء».' },
        { keys: ['وزن', 'سرعة', 'مواصفات', 'تشغيل'], reply: 'تبلغ بيانات البناء الحالية نحو 186 كغ، ومتوسط سرعة اختباري يقارب 30 كم/س، ومدة تشغيل تقديرية من ساعة إلى 3 ساعات بحسب الحمل.' },
        { keys: ['سلامة', 'خوذة', 'إيقاف', 'حزام'], reply: 'السلامة أولوية لا تقبل التنازل: مفتاح إيقاف طارئ وحزام أمان وخوذة وفحوصات متكررة قبل التشغيل.' },
        { keys: ['يوم السباق', 'موقع السباق', 'نتائج', 'السائق المختار'], reply: 'يعرض مركز «يوم السباق» التاريخ التخطيطي وحالة الموقع والجدول واختيار السائق والنتائج. التفاصيل غير المؤكدة تبقى مميزة بوضوح على أنها قيد التأكيد.' },
        { keys: ['بناء', 'مشروع', 'ورشة', 'مراحل', 'خطة'], reply: 'نخطط للسيارة ثم نجمعها ونثبت أداءها بالاختبارات. تابع صفحة «مشروعنا» للاطلاع على الرحلة كاملة.' },
        { keys: ['لعبة', 'كوبرا سيركت', 'نتيجة'], reply: 'العب Cobra Circuit في صفحة «اللعبة» واختر مستوى F3 أو F2 أو F1، ثم استخدم زر مشاركة النتيجة.' },
        { keys: ['موعد', 'أربعاء', 'خميس', 'نجتمع'], reply: 'يجتمع فريق كوبرا في غرفة السيارة الكهربائية يومي الأربعاء والخميس.' },
        { keys: ['انستغرام', 'إنستغرام', 'تيك توك', 'تواصل اجتماعي'], reply: 'تابع @sisaljadacobras على إنستغرام وتيك توك؛ ستجد الروابط في تذييل الموقع.' },
        { keys: ['مرحب', 'مساعدة', 'ماذا تستطيع', 'اهلا', 'أهلًا'], reply: 'مرحبًا، أنا CarGPT الخاص بفريق كوبرا سيس الجادة. اسألني عن المواصفات أو EVGP أو الرعاية أو قائمة السباق أو الأخبار أو اللعبة.' }
      ];
      for (const item of arabicAnswers) if (item.keys.some(k => q.includes(k))) return item.reply;
      return 'وضع الأسئلة الشائعة المحلي: اسأل عن الرعاية أو نظام 48 فولت أو EVGP أو الأخبار أو اللعبة، أو افتح صفحتي المواصفات وباقة الرعاية.';
    }
    const answers = [
      { keys: ['sponsor', 'contact', 'email', 'funding', 'partner'], reply: 'Open Sponsor Us or Sponsor Package, or message @sisaljadacobras on Instagram or TikTok. An official school sponsorship email has not been approved for publication.' },
      { keys: ['48v', '48 v', 'battery', 'voltage', 'electrical', 'power system'], reply: 'Our car runs on a 48V electric system built from four 12V batteries in series. We focus on clean wiring, labeled connections, and a kill switch.' },
      { keys: ['evgp', 'checklist', 'grand prix', 'february', 'competition', 'race day', 'venue', 'results'], reply: 'The planning target is 13 Feb 2027. Open Race Day for confirmed facts, driver selection, the provisional sequence, and official results when available; use Race Checklist for your device-local readiness list.' },
      { keys: ['news', 'update'], reply: 'See the News page for weekly workshop updates from the Cobras team.' },
      { keys: ['team', 'member', 'crew', 'who', 'students', 'how many'], reply: 'We are about 19 student builders at SABIS® Al Jada in Sharjah. Meet people on the Members page.' },
      { keys: ['weight', 'speed', 'spec', 'specs', 'runtime', 'km/h'], reply: 'Current build figures: about 186 kg, roughly 30 km/h average testing speed, and 1–3 hour runtime depending on load. Open Specs or the specs PDF.' },
      { keys: ['safety', 'helmet', 'kill switch', 'seat belt'], reply: 'Safety is non-negotiable: kill switch, seat belt, helmet, and repeatable pre-run checks.' },
      { keys: ['build', 'project', 'workshop', 'process', 'plan'], reply: 'We plan, assemble, then prove the car through testing. Follow Our Work for the full journey.' },
      { keys: ['game', 'cobra circuit', 'play', 'score'], reply: 'Play Cobra Circuit on the Game page (F3/F2/F1 modes) and use Share score to copy your result.' },
      { keys: ['meet', 'wednesday', 'thursday', 'schedule', 'club time'], reply: 'The Cobras meet in the Electric Car Room on Wednesdays and Thursdays.' },
      { keys: ['instagram', 'tiktok', 'social', 'follow'], reply: 'Follow @sisaljadacobras on Instagram and TikTok — links are in the footer.' },
      { keys: ['hello', 'hi', 'hey', 'help', 'what can'], reply: 'Hi—I am CarGPT for the SIS Al Jada Cobras. Ask about specs, EVGP, sponsorship, the checklist, news, or Cobra Circuit.' }
    ];
    for (const item of answers) {
      if (item.keys.some(k => q.includes(k))) return item.reply;
    }
    return 'Local FAQ mode: ask about sponsors, 48V, EVGP checklist, news, or the game—or open Specs and Sponsor Package.';
  }

  const api = {
    RACE_ISO,
    NAV_COLLAPSE_THRESHOLD,
    STRINGS,
    NAV_ITEMS,
    RESOURCE_ITEMS,
    normalizeLang,
    t,
    shouldCollapseNav,
    currentPageName,
    isCurrentNav,
    countdownParts,
    buildScoreShareText,
    checklistProgress,
    resolveChatConfig,
    trackPageView,
    localFaqReply
  };

  global.CobrasLib = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
